export const MARKETS = {
  BR: {
    locale: "pt-BR",
    currency: "BRL",
    texts: {
      title: "Calculadora financeira",
      discountTypeFidelity: "Desconto fidelidade",
      discountTypeSecondUnit: "Desconto na segunda unidade",
      priceLabel: "Valor Bruto",
      resaleLabel: "Valor de Revenda",
      discountLabel: "Desconto",
      marginLabel: "Margem de Lucro",
      finalPriceLabel: "Preço Final",
      discountWith: (n) => `Com ${n}% de desconto`,
      discountPlaceholder: "Com --% de desconto",
      marginHigh: "ALTA",
      marginMedium: "MÉDIA",
      marginLow: "BAIXA",
      howToUse: "Saiba como usar",
    },
  },
  CO: {
    locale: "es-CO",
    currency: "COP",
    texts: {
      title: "Calculadora financiera",
      discountTypeFidelity: "Descuento por fidelidad",
      discountTypeSecondUnit: "Descuento en la segunda unidad",
      priceLabel: "Precio bruto",
      resaleLabel: "Precio de reventa",
      discountLabel: "Descuento",
      marginLabel: "Margen de ganancia",
      finalPriceLabel: "Precio final",
      discountWith: (n) => `Con ${n}% de descuento`,
      discountPlaceholder: "Con --% de descuento",
      marginHigh: "ALTA",
      marginMedium: "MEDIA",
      marginLow: "BAJA",
      howToUse: "Cómo usar",
    },
  },
  CL: {
    locale: "es-CL",
    currency: "CLP",
    texts: {
      title: "Calculadora financiera",
      discountTypeFidelity: "Descuento por fidelidad",
      discountTypeSecondUnit: "Descuento en la segunda unidad",
      priceLabel: "Precio bruto",
      resaleLabel: "Precio de reventa",
      discountLabel: "Descuento",
      marginLabel: "Margen de ganancia",
      finalPriceLabel: "Precio final",
      discountWith: (n) => `Con ${n}% de descuento`,
      discountPlaceholder: "Con --% de descuento",
      marginHigh: "ALTA",
      marginMedium: "MEDIA",
      marginLow: "BAJA",
      howToUse: "Cómo usar",
    },
  },
  UY: {
    locale: "es-UY",
    currency: "UYU",
    texts: {
      title: "Calculadora financiera",
      discountTypeFidelity: "Descuento por fidelidad",
      discountTypeSecondUnit: "Descuento en la segunda unidad",
      priceLabel: "Precio bruto",
      resaleLabel: "Precio de reventa",
      discountLabel: "Descuento",
      marginLabel: "Margen de ganancia",
      finalPriceLabel: "Precio final",
      discountWith: (n) => `Con ${n}% de descuento`,
      discountPlaceholder: "Con --% de descuento",
      marginHigh: "ALTA",
      marginMedium: "MEDIA",
      marginLow: "BAJA",
      howToUse: "Cómo usar",
    },
  },
  MX: {
    locale: "es-MX",
    currency: "MXN",
    texts: {
      title: "Calculadora financiera",
      discountTypeFidelity: "Descuento por fidelidad",
      discountTypeSecondUnit: "Descuento en la segunda unidad",
      priceLabel: "Precio bruto",
      resaleLabel: "Precio de reventa",
      discountLabel: "Descuento",
      marginLabel: "Margen de ganancia",
      finalPriceLabel: "Precio final",
      discountWith: (n) => `Con ${n}% de descuento`,
      discountPlaceholder: "Con --% de descuento",
      marginHigh: "ALTA",
      marginMedium: "MEDIA",
      marginLow: "BAJA",
      howToUse: "Cómo usar",
    },
  },
};
